# .readthedocs.yaml

# Build documentation in the docs/ directory with Sphinx
# Docs: https://www.sphinx-doc.org/en/master/usage/configuration.html

version: 2

sphinx:
  configuration: ./source/conf.py

formats: all

# Optionally set the version of Python and requirements required to build your docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: ./requirements.txt
